#!/usr/bin/env python3
"""
Re-paste lib/f04 into the workflow JSON, replacing whatever snapshot is embedded there.

WHY THIS EXISTS
---------------
The deterministic scoring core lives in lib/f04/*.js under 141 unit tests. n8n Code nodes are
sandboxed and cannot `require` a repo file, so that source has to be embedded in the nodes.

Embedding it by hand freezes a snapshot. That already happened once: the workflows were built
with a paste taken before `independentSourceCount` existed and before `marketOutlook` was
renamed to `outlook`, so the running workflow was silently a version behind the tested module —
which is exactly the drift this whole feature is built to detect in other people's data.

So the paste is mechanical and repeatable instead. Run this after ANY change to lib/f04:

    python3 n8n/refresh-lib.py              # rewrite the JSON in place, syntax-check every node
    python3 n8n/refresh-lib.py --check      # report drift only, write nothing

Then redeploy (see n8n/workflows/README-f04.md).

HOW IT FINDS THE BLOCK
----------------------
Embedded blocks are wrapped as `const lib = (() => { ...source... })();` and open with a banner
containing "PASTED VERBATIM from lib/f04". This replaces everything between that IIFE's braces
with the current bundle, leaving the surrounding node logic untouched.
"""
import json
import os
import re
import subprocess
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LIBDIR = os.path.join(ROOT, 'lib', 'f04')
WFDIR = os.path.join(ROOT, 'n8n', 'workflows')

BANNER = "// ==== GENERATED by n8n/refresh-lib.py from lib/f04 -- do not edit inside n8n ===="
SHIM = ("// n8n's Code-node sandbox exposes no global URL, and NODE_FUNCTION_ALLOW_BUILTIN=url\n"
        "// only permits require('url') -- it does not inject the global. Without this the node\n"
        "// passes every syntax check and throws ReferenceError only at runtime.\n"
        "const { URL } = require('url');\n")


def bundle():
    parts = [BANNER, SHIM]
    for name in ('config', 'scoring', 'provenance'):
        src = open(os.path.join(LIBDIR, name + '.js'), encoding='utf-8').read()
        src = re.sub(r"const config = require\('\./config'\);", "", src)
        src = re.sub(r"const \w+ = require\('node:crypto'\);", "const crypto = require('crypto');", src)
        src = re.sub(r"const \{[^}]*?\}\s*=\s*config;", "", src, flags=re.S)
        src = re.sub(r"const \{[^}]*?\}\s*=\s*require\('\./[a-z]+'\);", "", src, flags=re.S)
        src = re.sub(r"module\.exports\s*=\s*\{.*?\};", "", src, flags=re.S)
        parts.append("// ===== lib/f04/%s.js =====\n%s" % (name, src))
    # The node code calls lib.<fn>(...), so the IIFE must return the public surface.
    exports = []
    for name in ('scoring', 'provenance'):
        m = re.search(r"module\.exports\s*=\s*\{(.*?)\};",
                      open(os.path.join(LIBDIR, name + '.js'), encoding='utf-8').read(), re.S)
        if m:
            exports += [x.strip() for x in m.group(1).split(',') if x.strip() and ':' not in x]
    parts.append("return { %s };" % ", ".join(sorted(set(exports))))
    return "\n".join(parts)


IIFE = re.compile(r"(const lib = \(\(\) => \{)(.*?)(\}\)\(\);)", re.S)


def refresh(js, new_bundle):
    if 'PASTED VERBATIM from lib/f04' not in js and BANNER not in js:
        return js, False
    out, n = IIFE.subn(lambda m: m.group(1) + "\n" + new_bundle + "\n" + m.group(3), js)
    return out, n > 0


def check_syntax(name, js):
    wrapped = ("(async function(){ const $env={},$input={first:()=>({json:{}})},$execution={id:1},"
               "$=()=>({first:()=>({json:{}})});\n" + js + "\n})")
    with tempfile.NamedTemporaryFile('w', suffix='.js', delete=False) as f:
        f.write(wrapped)
        p = f.name
    r = subprocess.run(['node', '--check', p], capture_output=True, text=True)
    os.unlink(p)
    if r.returncode:
        print("    SYNTAX ERROR in %s:\n%s" % (name, r.stderr[:300]))
    return r.returncode == 0


def main():
    check_only = '--check' in sys.argv
    b = bundle()
    print("bundle: %d bytes, exports: %s" % (len(b), b.rsplit('return {', 1)[1][:120].strip()))
    total_ok = True
    for fn in sorted(os.listdir(WFDIR)):
        if not fn.endswith('.json'):
            continue
        path = os.path.join(WFDIR, fn)
        wf = json.load(open(path, encoding='utf-8'))
        touched = 0
        for node in wf['nodes']:
            js = node.get('parameters', {}).get('jsCode')
            if not js:
                continue
            new, did = refresh(js, b)
            if did:
                touched += 1
                node['parameters']['jsCode'] = new
            if not check_syntax(node['name'], node['parameters'].get('jsCode', '')):
                total_ok = False
        print("  %-32s %d node(s) with an embedded lib block" % (wf['name'], touched))
        if touched and not check_only:
            json.dump(wf, open(path, 'w', encoding='utf-8'), indent=1)
    print("\nsyntax: %s" % ("all nodes OK" if total_ok else "FAILURES — not safe to deploy"))
    return 0 if total_ok else 1


if __name__ == '__main__':
    sys.exit(main())
