#!/usr/bin/env bash
# Load the anonymized demo dataset (db/fixtures/demo-seed.sql) into a target database.
#
# Usage:
#   DATABASE_URL="postgresql://<superuser>:<password>@<host>:<port>/postgres" ./db/load-demo.sh
#
# Notes:
# - Run db/apply.sh FIRST (schema + functions + views). This loader only ships data.
# - The seed is a pg_dump --data-only --disable-triggers dump: it wraps every table in
#   DISABLE/ENABLE TRIGGER ALL, which requires a SUPERUSER role at load time. On the
#   supabase/postgres image the `postgres` role is NOT superuser — use `supabase_admin`
#   (or pipe through `docker exec -i <db-container> psql -U supabase_admin ...`).
# - The seed contains registry/config rows (score_axes, metric_kinds, theses, ...) that
#   db/apply.sh also seeds, so this script TRUNCATEs all public tables first for a clean,
#   conflict-free load. Do NOT run it against a database whose data you want to keep.
# - The theses row ships WITH its original UUID so applications/scores/thesis_evaluations
#   FKs resolve (theses.id is a random UUID regenerated by apply.sh — a fresh apply's row
#   would not match; the truncate removes it and the seed's own row takes its place).
set -euo pipefail

cd "$(dirname "$0")/.."
SEED="db/fixtures/demo-seed.sql"
[ -f "$SEED" ] || { echo "ERROR: $SEED not found"; exit 1; }
: "${DATABASE_URL:?Set DATABASE_URL (superuser role — see header comments)}"

echo "==> Truncating public tables (clean load)"
psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -Atq <<'SQL' | psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f -
SELECT 'TRUNCATE TABLE '
       || string_agg(format('public.%I', tablename), ', ')
       || ' CASCADE;'
FROM pg_tables WHERE schemaname = 'public';
SQL

echo "==> Loading demo seed (this can take a minute)"
psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -q -f "$SEED"

echo "==> Row counts"
psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -P pager=off -c "
  SELECT 'founders' AS t, count(*) FROM founders
  UNION ALL SELECT 'companies', count(*) FROM companies
  UNION ALL SELECT 'applications', count(*) FROM applications
  UNION ALL SELECT 'claims', count(*) FROM claims
  UNION ALL SELECT 'scores', count(*) FROM scores
  UNION ALL SELECT 'memos', count(*) FROM memos;"

echo "==> Done. Reload PostgREST schema cache if serving REST:"
echo "    psql \"\$DATABASE_URL\" -c \"NOTIFY pgrst, 'reload schema'\""
