/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ATokenRouteImport } from './routes/a.$token'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as ApplyIndexRouteImport } from './routes/apply.index'
import { Route as ApplyQuestionsRouteImport } from './routes/apply.questions'
import { Route as ApplyStatusRouteImport } from './routes/apply.status'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ATokenRoute = ATokenRouteImport.update({
  id: '/a/$token',
  path: '/a/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApplyIndexRoute = ApplyIndexRouteImport.update({
  id: '/apply/',
  path: '/apply/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyQuestionsRoute = ApplyQuestionsRouteImport.update({
  id: '/apply/questions',
  path: '/apply/questions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyStatusRoute = ApplyStatusRouteImport.update({
  id: '/apply/status',
  path: '/apply/status',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/a/$token': typeof ATokenRoute
  '/apply/questions': typeof ApplyQuestionsRoute
  '/apply/status': typeof ApplyStatusRoute
  '/app/': typeof AppIndexRoute
  '/apply/': typeof ApplyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/a/$token': typeof ATokenRoute
  '/apply/questions': typeof ApplyQuestionsRoute
  '/apply/status': typeof ApplyStatusRoute
  '/app': typeof AppIndexRoute
  '/apply': typeof ApplyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/a/$token': typeof ATokenRoute
  '/apply/questions': typeof ApplyQuestionsRoute
  '/apply/status': typeof ApplyStatusRoute
  '/app/': typeof AppIndexRoute
  '/apply/': typeof ApplyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/privacy'
    | '/a/$token'
    | '/apply/questions'
    | '/apply/status'
    | '/app/'
    | '/apply/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/a/$token'
    | '/apply/questions'
    | '/apply/status'
    | '/app'
    | '/apply'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/privacy'
    | '/a/$token'
    | '/apply/questions'
    | '/apply/status'
    | '/app/'
    | '/apply/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ATokenRoute: typeof ATokenRoute
  ApplyQuestionsRoute: typeof ApplyQuestionsRoute
  ApplyStatusRoute: typeof ApplyStatusRoute
  ApplyIndexRoute: typeof ApplyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a/$token': {
      id: '/a/$token'
      path: '/a/$token'
      fullPath: '/a/$token'
      preLoaderRoute: typeof ATokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/apply/': {
      id: '/apply/'
      path: '/apply'
      fullPath: '/apply/'
      preLoaderRoute: typeof ApplyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/questions': {
      id: '/apply/questions'
      path: '/apply/questions'
      fullPath: '/apply/questions'
      preLoaderRoute: typeof ApplyQuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/status': {
      id: '/apply/status'
      path: '/apply/status'
      fullPath: '/apply/status'
      preLoaderRoute: typeof ApplyStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ATokenRoute: ATokenRoute,
  ApplyQuestionsRoute: ApplyQuestionsRoute,
  ApplyStatusRoute: ApplyStatusRoute,
  ApplyIndexRoute: ApplyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
