/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ATokenRouteImport } from './routes/a.$token'
import { Route as ApplyQuestionsRouteImport } from './routes/apply.questions'
import { Route as ApplyStatusRouteImport } from './routes/apply.status'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ATokenRoute = ATokenRouteImport.update({
  id: '/a/$token',
  path: '/a/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyQuestionsRoute = ApplyQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => ApplyRoute,
} as any)
const ApplyStatusRoute = ApplyStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => ApplyRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/a/$token': typeof ATokenRoute
  '/apply/questions': typeof ApplyQuestionsRoute
  '/apply/status': typeof ApplyStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/a/$token': typeof ATokenRoute
  '/apply/questions': typeof ApplyQuestionsRoute
  '/apply/status': typeof ApplyStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apply': typeof ApplyRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/a/$token': typeof ATokenRoute
  '/apply/questions': typeof ApplyQuestionsRoute
  '/apply/status': typeof ApplyStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apply'
    | '/privacy'
    | '/a/$token'
    | '/apply/questions'
    | '/apply/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apply'
    | '/privacy'
    | '/a/$token'
    | '/apply/questions'
    | '/apply/status'
  id:
    | '__root__'
    | '/'
    | '/apply'
    | '/privacy'
    | '/a/$token'
    | '/apply/questions'
    | '/apply/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplyRoute: typeof ApplyRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ATokenRoute: typeof ATokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a/$token': {
      id: '/a/$token'
      path: '/a/$token'
      fullPath: '/a/$token'
      preLoaderRoute: typeof ATokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/questions': {
      id: '/apply/questions'
      path: '/questions'
      fullPath: '/apply/questions'
      preLoaderRoute: typeof ApplyQuestionsRouteImport
      parentRoute: typeof ApplyRoute
    }
    '/apply/status': {
      id: '/apply/status'
      path: '/status'
      fullPath: '/apply/status'
      preLoaderRoute: typeof ApplyStatusRouteImport
      parentRoute: typeof ApplyRoute
    }
  }
}

interface ApplyRouteChildren {
  ApplyQuestionsRoute: typeof ApplyQuestionsRoute
  ApplyStatusRoute: typeof ApplyStatusRoute
}

const ApplyRouteChildren: ApplyRouteChildren = {
  ApplyQuestionsRoute: ApplyQuestionsRoute,
  ApplyStatusRoute: ApplyStatusRoute,
}

const ApplyRouteWithChildren = ApplyRoute._addFileChildren(ApplyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplyRoute: ApplyRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ATokenRoute: ATokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
